AnimationController -> DomElementModel
AnimationController -> TextController
AnimationController -> TextModel
CharController -> RandomCharModel
CharController -> DomElementModel
CharController -> Utilities
TextController -> CharController
TextController -> TextModel
TextController -> DomElementModel

DomElementModel -> HTMLElement
DomElementModel -> Utilities
RandomCharModel -> Utilities



